# Generated by Django 4.0 on 2021-12-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('categoria', models.CharField(choices=[('BASICO', 'Basico'), ('PREMIUM', 'Premium')], default='BASICO', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('precio', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
